symbols:
  - XLMUSDT
  - XECUSDT
  - TRVLUSDT
  - SANDUSDC
  - MXUSDT
  - NFTUSDT
  - NEXOUSDT
  - JASMYUSDT
  - LOOKSUSDT
  - DGBUSDT
  - DOGEUSDT
  - 1INCHUSDT
  - AAVEUSDT
  - ALGOUSDT
  - ANKRUSDT
  - ATOMUSDT
  - AVAUSDT
  - YFIUSDT
  - WAVESUSDT
  - SUNUSDT
  - UMAUSDT
  - RVNUSDT
  - RSS3USDT
  - SOLUSDC
  - IMXUSDT
  - KASTAUSDT
  - HBARUSDT
  - FILUSDT
  - ERTHAUSDT
  - USDCUSDT
  - SISUSDT
  - SLPUSDT
  - PERPUSDT
  - JSTUSDT
  - ALGOBTC
  - GALAUSDT
  - HNTUSDT
  - BTTUSDT
  - AVAXUSDT
  - XEMUSDT
  - ZENUSDT
  - ZRXUSDT
  - STETHUSDT
  - QNTUSDT
  - SHIBUSDT
  - ONEUSDT
  - LTCBTC
  - LTCUSDC
  - LUNCUSDT
  - ADAUSDT
