symbols:
  - XLMUSDT
  - XECUSDT
  - TRVLUSDT
  - SANDUSDC
  - MXUSDT
  - NEARUSDT
  - JASMYUSDT
  - DOGEUSDT
  - AAVEUSDT
  - 1INCHUSDT
  - LOOKSUSDT
  - DGBUSDT
  - GMTUSDC
  - NEXOUSDT
  - PRIMEUSDT
  - INTERUSDT
  - LINKUSDC
  - MOVRUSDT
  - RPLUSDT
  - SANDUSDT
