backtest:
  adaptive_thresholds: true
  adf_pvalue_threshold: 0.05
  annualizing_factor: 365
  anti_churn_cooldown_minutes: 60
  beta_recalc_frequency_hours: 48
  beta_window_days_max: 120
  beta_window_days_min: 60
  cointegration_test_frequency: 2688
  commission_pct: 0.0004
  commission_rate_per_leg: 0.0004
  cooldown_hours: 4
  correlation_window: 720
  enable_funding_time_filter: true
  enable_macro_event_filter: true
  enable_pair_quarantine: false
  enable_realistic_costs: true
  exclusion_period_days: 30
  fill_limit_pct: 0.1
  funding_blackout_minutes: 30
  funding_cost_enabled: true
  funding_reset_hours:
  - 0
  - 8
  - 16
  hurst_trending_threshold: 0.5
  hurst_window: 720
  macro_blackout_minutes: 30
  market_regime_detection: true
  max_half_life_days: 14
  max_kelly_fraction: 0.25
  max_var_multiplier: 3.0
  min_correlation_threshold: 0.6
  min_position_hold_minutes: 60
  min_spread_move_sigma: 0.1
  pair_stop_loss_usd: 75.0
  pair_stop_loss_zscore: 3.0
  portfolio_daily_stop_pct: 0.02
  quarantine_drawdown_threshold_pct: 0.08
  quarantine_period_days: 7
  quarantine_pnl_threshold_sigma: 3.0
  quarantine_rolling_window_days: 30
  rolling_window: 30
  slippage_half_spread_multiplier: 2.0
  slippage_pct: 0.0005
  stop_loss_multiplier: 4.026417440353877
  structural_break_protection: true
  take_profit_multiplier: null
  time_stop_multiplier: 2.876666441341353
  timeframe: 15min
  use_kelly_sizing: true
  use_ols_beta_sizing: true
  var_confidence: 0.05
  variance_ratio_mean_reverting_max: 0.8
  variance_ratio_trending_min: 1.2
  variance_ratio_window: 480
  volatility_lookback: 96
  zscore_entry_threshold: 1.500147431951228
  zscore_exit: -0.13655478260489132
  zscore_threshold: 1.500147431951228
data_dir: !!python/object/apply:pathlib.PosixPath
- data_downloaded
data_processing:
  fill_method: linear
  handle_constant: true
  min_history_ratio: 0.8
  normalization_method: minmax
filter_params:
  max_beta: 10.0
  max_half_life_days: 252.0
  max_hurst_exponent: 0.5
  min_beta: 0.1
  min_half_life_days: 1.0
  min_mean_crossings: 10
max_shards: null
pair_selection:
  adaptive_quantiles: false
  bar_minutes: 15
  coint_pvalue_threshold: 0.1
  cost_filter: null
  enable_pair_tradeability_filter: true
  kpss_pvalue_threshold: 0.005
  liquidity_usd_daily: 100000.0
  lookback_days: 60
  max_avg_funding_pct: 0.05
  max_bid_ask_pct: 0.5
  max_funding_rate_abs: 0.001
  max_half_life_days: 30.0
  max_half_life_hours: 720.0
  max_hurst_exponent: 0.5
  max_tick_size_pct: 0.002
  min_abs_spread_mult: null
  min_days_live: 7
  min_half_life_days: 0.5
  min_mean_crossings: 5
  min_volume_usd_24h: 200000.0
  pvalue_top_n: 500
  save_filter_reasons: true
  save_std_histogram: true
  ssd_top_n: 50000
portfolio:
  f_max: 0.25
  initial_capital: 10000.0
  leverage_limit: 2.0
  max_active_positions: 5
  max_margin_usage: 0.5
  max_notional_per_trade: 10000.0
  max_position_size_pct: 0.10938238251167777
  min_notional_per_trade: 100.0
  min_position_size_pct: 0.005
  risk_per_position_pct: 0.01532529265129277
  volatility_adjustment_factor: 2.0
  volatility_based_sizing: true
  volatility_lookback_hours: 24
results_dir: !!python/object/apply:pathlib.PosixPath
- results
walk_forward:
  end_date: '2024-02-08'
  start_date: '2024-01-15'
  testing_period_days: 3
  training_period_days: 10
